### PR TITLE
add username validators

### PR DESCRIPTION
**Pull request by ro0NL**
first backport from #42 

plan is to add configuration to enable secondary username lookups, i.e. using e-mail as username + UserSecondaryEmail. In case config might look like:

```
msgphp_user:
  username_lookup:
    - { target: UserSecondaryEmail, fields: [email], mapped_my: user }
```

`user.credential.username` is looked up by default.

Goal is to make `UserRepo::findByUsername` aware of secondary usernames eventually.

### CODE REVIEW

**Comment by iltar** [comment]
Why bother having this validation tbh? If 2 usernames are added at the same time, neither will say it's taken and then 1 will get a unique constraint error.

**Comment by ro0NL** [comment]
yeah.. isnt that an edge case for _end users_? Given a a nice form error upfront avoid 99.9% of such cases?

**Comment by ro0NL** [comment]
to reverse the logic we could als ship a `Username` entity, which we enable in case of secondary username lookups are configured. Then we can keep a single table of unique usernames..

Not sure if the repository should sync usernames or the command :thinking:

**Comment by iltar** [comment]
Case (A) covers 99.9% of the case. Case (B) covers 100% of the cases. Why have both A and B then?

**Comment by ro0NL** [comment]
Im going for a `Username` entity to provide a single source of truth, and one can indeed rely on the unique constraint error to act upon.

I dont see any real reason to not ship validators for this; they can be needed elsewhere for something that is not insert related or so.

Ill update the demo app (once ready) with a register page using case B.

**Pull request merged**
