### PR TITLE
introducing various domain id data types

### LINKED ISSUE #3: Investigate binary UUID
https://github.com/spatie/uuid-mysql-performance

`UserId::toBinary` + specialized doctrine type? configurable?

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #3 if it comes with binary uuid implem. Could be a separate PR as well after this.

The plan;

- generics (core domain)
  - `DomainId`
  - `Infra\Uuid\DomainId`
- concrete (per domain)
  - `UserId`
  - `Infra\Uuid\UserId`
- types (core domain)
  - `Infra\Doctrine\DomainIdType`
- config (per bundle)

```yaml
parameters:
  default_id_data_type: integer

msghp_user:
  default_id_data_type: '%msgphp.default_id_data_type%'
  id_data_types:
    UserIdInterface: uuid | binary_uuid | string | integer | <custom-name>
```

The bundles will configure the doctrine type per domain id type (using a global name, i.e. `msgphp_user_id`, etc.). Happens static by design.

All data type variations on instance level in the doctrine type are flagged static from the bundle, i.e. which concrete class to return as PHP value (resolved from the bundle config's class mapping). And which data type implementation to use to vary the schema options; in case the latter is `<custom-name>` we'll forward everything to another type; as we can get that static.

For the class mapping; it will default to `UserId`. If the data type is `uuid | binary_uuid` we'll default to `Infra\Uuid\UserId` or crash if ramsey/uuid package is unavailable.

ping @kejwmen :)

### CODE REVIEW

**Comment by kejwmen** [comment]
I never looked at this problem from library perspective.

Read summary and it looks really nice, but I will take a closer look at implementation later.

Thanks for pinging ;)

**Comment by ro0NL** [comment]
> I never looked at this problem from library perspective.

Well. join the club :) it was a bit more work as expected. Mostly because doctrine's type system is static and requires special code paths.

For now 2 things left; varying the concrete class used based on data type (should be easy), and enabling a strategy (AUTO default) for integer data type.

In general the bundle config _simply_ automates the `doctrine.dbal.types` config. It shouldnt be too complex for end-users.

**Comment by ro0NL** [comment]
ok starting to work out :)

default:

```
CREATE TABLE attribute_value (id INT AUTO_INCREMENT NOT NULL COMMENT '(DC2Type:msgphp_attribute_value_id)', ...
```

setting `parameters: { msgphp.default_data_type: uuid }`

```
CREATE TABLE attribute_value (id CHAR(36) NOT NULL COMMENT '(DC2Type:msgphp_attribute_value_id)', ...
```

setting `parameters: { msgphp.default_data_type: uuid_binary }`

```
CREATE TABLE attribute_value (id BINARY(16) NOT NULL COMMENT '(DC2Type:msgphp_attribute_value_id)', ...
```

Sweeet :)

**Comment by ro0NL** [comment]
Done on my side. Merging tonight!

**Pull request merged**
