### PR TITLE
[WIP] Introduce PHP library starter kit

### PR DESCRIPTION
**Pull request by jkabat**
@ro0NL Im trying to follow your suggestion about improving msgPHP library.

For the start I have added starter kit to the monorepo only. Github actions report is in my own fork. As you can see we have to decide on matrix to be used:

- OS: supporting ubuntu might be enough
- PHP: as ramsey/devtools has dependancy on PHP 7.4, can we drop support of 7.2 and 7.3?
- DEPs: highest dependencies fails due to a issue with DBAL v3+
- Tools:
  - CS fails with unknown error, I need to investigate
  - PHPstan should be disabled until we start new branch with related fixes

Please let me know what do you think.

### CODE REVIEW

**Comment by jkabat** [comment]
@ro0NL bump

Can I continue? Are you willing to discuss the changes and possible merge of PR?

**Comment by ro0NL** [comment]
@jkabat i can make you admin too :cat: (you can DM me on Synfony slack)

**Comment by jkabat** [comment]
@ro0NL I have bumped to php 7.4, fixed dependency hell to be prepared for upgrading to more recent versions. Still need to resolve PSALM issues I'm not familiar with very much.

Will contact you on slack next week.

**Comment by ro0NL** [comment]
let me know if you want a merge to see what GH actions does.

furthermore i'd opt for symfony >= 5.4 + php >=7.4 support

**Comment by jkabat** [comment]
We can merge it, but there will be fail for Static analysis step. Maybe somebody more experienced can take a look at psalm issues, I would continue with deprecations and upgrades. WDYT?

**Comment by jkabat** [comment]
Understood. I will continue on my branch then. Thanks for interesting project regardless.

**Pull request closed without merging**
