### PR TITLE
update phpstan config

### PR DESCRIPTION
**Pull request by ro0NL**
should be good now

### CODE REVIEW

**Comment by GawainLynch** [comment]
Shouldn't the root `composer.json` be updated to `"phpstan/phpstan": "^0.9.2",`?

**Comment by ro0NL** [comment]
back to `^0.9` then? Idea of the `@dev` constraint for phpstan was to keep up with latest checks & finetuning...

**Comment by GawainLynch** [comment]
Well, < 0.9.2 will fail test was my thinking  … but yeah, keeping it tracking `@dev` is also fine

**Comment by ro0NL** [comment]
we dont prefer lowest phpstan anyway ;-)

**Pull request merged**
